db:
  repository: public.ecr.aws/n4q9v7r0/jh-lab2
  tag: db-v1
  replicas: 1

redis:
  repository: public.ecr.aws/n4q9v7r0/jh-lab2
  tag: redis-v1
  replicas: 1

app:
  repository: public.ecr.aws/n4q9v7r0/jh-lab2
  tag: app-v1
  replicas: 2

nginx:
  repository: nginx
  tag: latest
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: app.jeonghwa.shop
  certificateArn: arn:aws:acm:ap-northeast-1:569934397842:certificate/ee2d8904-6727-491e-b1aa-cb04163d3660
  group:
    name: shared-alb
    order: "10"
